Server/Server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Server/post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_create/', views.post_create, name = 'post_create'),
    path('<int:post_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/like/', views.like, name='like'),
    path('<int:post_pk>/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]

Server/post/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name='포스트 제목')
    image = models.ImageField(blank=True, upload_to='post', verbose_name='이미지')
    content = models.TextField(verbose_name='내용')
    like_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str(self):
        return self.content

Server/post/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

Server/post/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm


def post_list(request):
    posts = Post.objects.all()
    ctx = {'posts': posts}
    return render(request, 'post/base.html', ctx)


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            post = form.save()
            return redirect('post:post_list')
    else:
        form = PostForm()
    return render(request, "post/post_create.html", {'form': form})


def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        content = request.POST['comment']  # comment의 content 가져오기
        comment = Comment.objects.create(post=post, content=content)
        comment.save()
        return redirect('post:post_list')

def like(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        if post.like_status is False:
            Post.objects.filter(pk=post_pk).update(like_status=True)
        else:
            Post.objects.filter(pk=post_pk).update(like_status=False)
    return redirect('post:post_list')

def comment_delete(request, post_pk, comment_pk):
    post=Post.objects.get(pk=post_pk)
    comment=post.comment_set.get(pk=comment_pk)
    if request.method =='POST':
        comment.delete()
        return redirect('post:post_list')
    else:
        return redirect('post:post_list')

Server/post/templates/post/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Post</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'base.css'%}">
  </head>
  <body>
    <div class="nav_bar">
        <p>Pirostagram</p>
        <a href="{% url 'post:post_create' %}">게시물 작성</a>
    </div>

    {% block content %}

    {% for post in posts %}
    <div class="post">
        <div class="image"><img src="{{post.image.url}}" alt="img" style="width: 400px; height: 400px"/></div>
        <div class="post_content">
            <h3>{{post.title}}</h3>
            <textarea rows="4" readonly="readonly">{{post.content}}</textarea>

            {% comment %} 작성된 댓글 {% endcomment %}
            <p style="text-align:center;">댓글</p>
            <hr />
            {% for comment in post.comment_set.all %}
            <div class='comment_box'>
                <p>{{comment.content}}</p>
                <form action="{% url 'post:comment_delete' post.id comment.id %}" method ='POST'>
                    {% csrf_token %}
                    <input name="comment_delete" type="submit" value="X" />
                </form>
            </div>
            {% endfor %}

            {% comment %} 좋아요 {% endcomment %} 
            {% if post.like_status == True %}
            <div class='like_box'>
                <form action="{% url 'post:like' post.id %}" method="POST">
                {% csrf_token %}
                <button type='submit'><i class="fas fa-heart"></i></button>
                </form>
                <span>이 게시물에 좋아요를 눌렀습니다.</span>
            </div>

            {% elif post.like_status == False %}
            <div class='dislike_box'>
                <form action="{% url 'post:like' post.id %}" method="POST">
                {% csrf_token %}
                <button type='submit'><i class="far fa-heart"></i></button>
                </form>
                <span>게시물이 좋으면 좋아요를 눌러주세요!</span>
            </div>
            {% endif %} 
            
            {% comment %} 댓글 작성 {% endcomment %}
            <div class="register_comment">
                <form action="{% url 'post:comment_create' post.id %}" method="POST">
                {% csrf_token %}
                    <input class='txt' type="text" name="comment" placeholder="댓글 달기...." style="width:395px; height:50px;" />
                    <input class='btn' type="submit" value="게시" />
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

    {% endblock %}

  </body>
</html>

Server/post/templates/post/post_create.html
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="form_table">
    <td>{{ form.as_table }}</td>
    <td><input class="button_" type="submit" value="submit" /></td>
  </table>
</form>